Fix/nav foot
tech-university-india/uhi-onboarding-frontend pull request #17
Opened 2023-02-17 11:52 UTC by Saatwik-S

- Optimised. the footer code
-  Add login link in the Navbar

2023-02-17 13:28 UTC, rkdixit96 requested changes

2023-02-17 13:28 UTC, rkdixit96 commented on src/components/Footer/index.jsx
> +  const footerChildren = [
Move to screen text file

2023-02-17 16:13 UTC, rkdixit96 approved these changes

2023-02-19 16:12 UTC, shreyas1925 approved these changes

2023-02-19 16:13 UTC, merged