feat: render aadhar photo and add qrCode modal
tech-university-india/uhi-onboarding-frontend pull request #24
Opened 2023-03-05 13:29 UTC by shreyas1925

- [ ] Rendered QR code in 64 base image format which can be use to render Aadhaar photo from API.
- [ ] Example of how we can use QR Modal in Profile page
<img width="733" alt="qrCode" src="https://user-images.githubusercontent.com/70105807/222963306-94914999-a34a-436c-8cee-80c4acd833b8.png">
- [ ] Modal View 
<img width="316" alt="Screenshot 2023-03-05 at 6 50 21 PM" src="https://user-images.githubusercontent.com/70105807/222963348-ae7feea8-5d6a-4a7d-b4c3-295e46f8d917.png">

2023-03-05 16:52 UTC, SaatwikRishi requested changes
please pull the latest main commit and add tests

2023-03-06 16:37 UTC, rkdixit96 requested changes
Why is there a diff in package-lock.json without an update to package.json?

2023-03-13 09:28 UTC, Kushagraved approved these changes

2023-03-13 09:35 UTC, ishit-007 approved these changes

2023-03-13 10:07 UTC, souris-dev approved these changes

2023-03-13 10:52 UTC, merged