feat: add textboxes
tech-university-india/uhi-onboarding-frontend pull request #27
Opened 2023-03-06 09:06 UTC by souris-dev

Add custom textbox component.

2023-03-06 16:26 UTC, rkdixit96 requested changes

2023-03-07 02:55 UTC, souris-dev commented on src/components/TextBox/index.jsx
> +  const PAD_PARTIAL_TEXT_NO_DOT = 0.68
These constants are used to calculate the amount of padding needed for the text being typed in into the textbox so that it doesn't overlap with the fixed (partial) text.

2023-03-07 02:56 UTC, souris-dev commented on src/components/TextBox/index.jsx
> +import styles from './TextBox.module.css'
Rightly pointed out, it should be possible with tailwind as well, let me try to use tailwind to achieve it.

2023-03-07 02:56 UTC, souris-dev commented on src/components/TextBox/index.jsx
> +            onChange={onChange}
Sure, will do so

2023-03-07 04:01 UTC, rkdixit96 approved these changes

2023-03-13 07:41 UTC, Kushagraved approved these changes

2023-03-13 08:41 UTC, merged