Feat/patient onboarding
tech-university-india/uhi-onboarding-frontend pull request #4
Opened 2023-02-01 05:32 UTC by Kushagraved

add conditional rendering for otp

2023-02-07 15:00 UTC, rkdixit96 requested changes

2023-02-07 15:00 UTC, rkdixit96 commented on src/app/layout.jsx
> +
Fix liniting

2023-02-07 15:00 UTC, rkdixit96 commented on src/app/page.jsx
> +    <h1 className='text-3xl font-bold text-red-500' >Hello World</h1>
Move text to screen text

2023-02-07 15:00 UTC, rkdixit96 commented on src/components/AadharForm.js
> +      router.reload(window.location.pathname)
Lets remove router - Just clear state if error

2023-02-07 15:00 UTC, rkdixit96 commented on src/components/AadharForm.js
> +    const validationRegex = /^\d{4}\s?\d{4}\s?\d{4}$/;
Move regex to config file

2023-02-07 15:00 UTC, rkdixit96 commented on src/components/AadharForm.js
> +    console.log(input);
Remove this

2023-02-07 15:00 UTC, rkdixit96 commented on src/components/AadharForm.js
> +                </div>
Split into components - This is too big

2023-02-07 15:00 UTC, rkdixit96 commented on src/components/Footer.js
> +
Split into components - File is too big

2023-02-09 12:48 UTC, ishit-007 commented
Patient Onboarding PR

2023-02-09 12:54 UTC, merged